version: '3.8'

services:
  fastapi-summarizer:
    build: .
    container_name: fastapi-summarizer
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
